apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: akeenan-poi-map-app-dev
  annotations:
    argocd/app-name: akeenan-poi-map-app-dev
    backstage.io/kubernetes-id: akeenan-poi-map-app
    backstage.io/kubernetes-namespace: akeenan
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/akeenan-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/akeenan/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/akeenan/deployments/akeenan-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/akeenan-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://akeenan-poi-map-app-akeenan.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/akeenan"
  system: workshop-system-akeenan
  consumesApis:
    - gateway-api-akeenan
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-akeenan
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/akeenan"
